/* ---------------------------------------------------------------
   LANGUAGE + SPEECH RECOGNITION CODES
----------------------------------------------------------------*/
export const LANGS = [
  { id: "en", label: "English" },
  { id: "hi", label: "हिंदी" },
  { id: "ta", label: "தமிழ்" },
  { id: "bn", label: "বাংলা" },
];

export const SPEECH_LANG_CODES = {
  en: "en-IN",
  hi: "hi-IN",
  ta: "ta-IN",
  bn: "bn-IN",
};

/* ---------------------------------------------------------------
   UI STRINGS — every screen reads from this per selected language
----------------------------------------------------------------*/
export const STRINGS = {
  en: {
    consentTitle: "Confirm your identity & consent",
    consentSub: "Your history is linked to your ABHA health account under the Ayushman Bharat Digital Mission.",
    abhaLabel: "ABHA ID or Aadhaar-linked number",
    newPatient: "New patient — register without ABHA →",
    consentStore: "I consent to my spoken history and scanned documents being processed to build my medical record.",
    consentShare: "I consent to this record being shared with my treating physician and linked to my ABHA account.",
    consentAudio: "Read this consent aloud to me in my language before I continue.",
    agreeBtn: "Agree & begin history",
    questionsAnswered: (n) => `${n} question${n > 1 ? "s" : ""} answered so far`,
    priorityTitle: "Priority flag raised.",
    priorityBody: "Triage staff have been alerted — this patient will be seen out of turn.",
    micListening: "Listening…",
    micIdle: "Or type / speak your own answer",
    nextBtn: "Next",
    micUnsupported: "Voice input isn't supported in this browser. Please type your answer, or try Chrome.",
    micDenied: "Microphone access is blocked. Allow the microphone permission for this site and try again.",
    micNoSpeech: "Didn't catch that. Please try again or type your answer.",
    micGenericError: "Voice input hit a snag. Please type your answer.",
    scanTitle: "Scan your prior medical documents",
    scanSub: "Upload a photo or PDF of a prescription, lab report, or discharge summary, if you have one.",
    uploadPrompt: "Tap to upload, or drag files here",
    uploadHint: "Prescriptions, lab reports, discharge summaries — JPG, PNG, or PDF, up to 15MB each",
    skipStep: "Skip this step",
    continueSummary: "Continue to summary",
    buildingSummary: "Building your history summary…",
    buildingSummarySub: "MediKiosk is combining your answers and documents into one clinical summary.",
    summaryReady: "Your history is ready",
    summaryReadyBody: "Please listen and confirm — your physician will review this at consultation.",
    confirmSend: "Confirm & send to physician",
    sentTitle: "Sent to your doctor",
    sentBody: "Your history has been linked to your ABHA record and pushed to the hospital system. Please take a seat — you'll be called by token number shortly.",
    seePhysician: "See what the physician sees →",
  },
  hi: {
    consentTitle: "अपनी पहचान और सहमति की पुष्टि करें",
    consentSub: "आयुष्मान भारत डिजिटल मिशन के तहत आपका इतिहास आपके ABHA हेल्थ खाते से जुड़ा है।",
    abhaLabel: "ABHA आईडी या आधार-लिंक्ड नंबर",
    newPatient: "नया मरीज़ — बिना ABHA के पंजीकरण करें →",
    consentStore: "मैं सहमति देता/देती हूं कि मेरा बोला गया इतिहास और स्कैन किए गए दस्तावेज़ मेरा मेडिकल रिकॉर्ड बनाने के लिए संसाधित किए जाएं।",
    consentShare: "मैं सहमति देता/देती हूं कि यह रिकॉर्ड मेरे डॉक्टर के साथ साझा किया जाए और मेरे ABHA खाते से जोड़ा जाए।",
    consentAudio: "आगे बढ़ने से पहले यह सहमति मुझे मेरी भाषा में सुनाएं।",
    agreeBtn: "सहमत हूं और इतिहास शुरू करें",
    questionsAnswered: (n) => `अब तक ${n} सवालों के जवाब दिए गए`,
    priorityTitle: "प्राथमिकता चेतावनी दी गई।",
    priorityBody: "ट्राइएज स्टाफ को सूचित कर दिया गया है — इस मरीज़ को बिना बारी के देखा जाएगा।",
    micListening: "सुन रहा है…",
    micIdle: "या अपना जवाब टाइप करें / बोलें",
    nextBtn: "आगे",
    micUnsupported: "इस ब्राउज़र में आवाज़ इनपुट समर्थित नहीं है। कृपया टाइप करें, या Chrome आज़माएं।",
    micDenied: "माइक्रोफ़ोन एक्सेस अवरुद्ध है। इस साइट के लिए माइक्रोफ़ोन अनुमति दें और फिर से कोशिश करें।",
    micNoSpeech: "आवाज़ स्पष्ट नहीं आई। कृपया फिर से कोशिश करें या टाइप करें।",
    micGenericError: "आवाज़ इनपुट में समस्या आई। कृपया टाइप करें।",
    scanTitle: "अपने पुराने मेडिकल दस्तावेज़ स्कैन करें",
    scanSub: "यदि आपके पास पर्ची, लैब रिपोर्ट या डिस्चार्ज सारांश है, तो उसकी फ़ोटो या PDF अपलोड करें।",
    uploadPrompt: "अपलोड करने के लिए टैप करें, या फ़ाइलें यहाँ खींचें",
    uploadHint: "पर्ची, लैब रिपोर्ट, डिस्चार्ज सारांश — JPG, PNG, या PDF, प्रत्येक 15MB तक",
    skipStep: "यह चरण छोड़ें",
    continueSummary: "सारांश पर जारी रखें",
    buildingSummary: "आपका इतिहास सारांश बनाया जा रहा है…",
    buildingSummarySub: "MediKiosk आपके जवाबों और दस्तावेज़ों को एक क्लिनिकल सारांश में जोड़ रहा है।",
    summaryReady: "आपका इतिहास तैयार है",
    summaryReadyBody: "कृपया सुनें और पुष्टि करें — आपका डॉक्टर परामर्श के समय इसकी समीक्षा करेगा।",
    confirmSend: "पुष्टि करें और डॉक्टर को भेजें",
    sentTitle: "आपके डॉक्टर को भेज दिया गया",
    sentBody: "आपका इतिहास आपके ABHA रिकॉर्ड से जोड़कर अस्पताल प्रणाली में भेज दिया गया है। कृपया बैठें — जल्द ही आपका टोकन नंबर पुकारा जाएगा।",
    seePhysician: "देखें डॉक्टर को क्या दिखता है →",
  },
  ta: {
    consentTitle: "உங்கள் அடையாளம் மற்றும் ஒப்புதலை உறுதிப்படுத்தவும்",
    consentSub: "ஆயுஷ்மான் பாரத் டிஜிட்டல் மிஷன் கீழ் உங்கள் வரலாறு உங்கள் ABHA சுகாதார கணக்குடன் இணைக்கப்பட்டுள்ளது.",
    abhaLabel: "ABHA ஐடி அல்லது ஆதார் இணைந்த எண்",
    newPatient: "புதிய நோயாளி — ABHA இல்லாமல் பதிவு செய்ய →",
    consentStore: "எனது பேசிய வரலாறு மற்றும் ஸ்கேன் செய்யப்பட்ட ஆவணங்கள் எனது மருத்துவ பதிவை உருவாக்க செயலாக்கப்படுவதற்கு நான் ஒப்புக்கொள்கிறேன்.",
    consentShare: "இந்த பதிவு எனது மருத்துவருடன் பகிரப்பட்டு எனது ABHA கணக்குடன் இணைக்கப்படுவதற்கு நான் ஒப்புக்கொள்கிறேன்.",
    consentAudio: "தொடர்வதற்கு முன் இந்த ஒப்புதலை எனது மொழியில் படித்துக் காட்டவும்.",
    agreeBtn: "ஒப்புக்கொண்டு வரலாற்றைத் தொடங்கு",
    questionsAnswered: (n) => `இதுவரை ${n} கேள்விகளுக்கு பதிலளிக்கப்பட்டது`,
    priorityTitle: "முன்னுரிமை எச்சரிக்கை எழுப்பப்பட்டது.",
    priorityBody: "டிரையேஜ் பணியாளர்களுக்கு தெரிவிக்கப்பட்டுள்ளது — இந்த நோயாளி வரிசை இல்லாமல் பார்க்கப்படுவார்.",
    micListening: "கேட்கிறது…",
    micIdle: "அல்லது உங்கள் பதிலை தட்டச்சு செய்யவும் / பேசவும்",
    nextBtn: "அடுத்து",
    micUnsupported: "இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை. தட்டச்சு செய்யவும், அல்லது Chrome ஐ பயன்படுத்தவும்.",
    micDenied: "மைக்ரோஃபோன் அணுகல் தடுக்கப்பட்டது. இந்த தளத்திற்கு மைக்ரோஃபோன் அனுமதி வழங்கி மீண்டும் முயற்சிக்கவும்.",
    micNoSpeech: "தெளிவாக கேட்கவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது தட்டச்சு செய்யவும்.",
    micGenericError: "குரல் உள்ளீட்டில் சிக்கல். தட்டச்சு செய்யவும்.",
    scanTitle: "உங்கள் முந்தைய மருத்துவ ஆவணங்களை ஸ்கேன் செய்யவும்",
    scanSub: "உங்களிடம் மருந்துச் சீட்டு, ஆய்வக அறிக்கை அல்லது டிஸ்சார்ஜ் சுருக்கம் இருந்தால், அதன் புகைப்படம் அல்லது PDF-ஐ பதிவேற்றவும்.",
    uploadPrompt: "பதிவேற்ற தட்டவும், அல்லது கோப்புகளை இங்கே இழுக்கவும்",
    uploadHint: "மருந்துச் சீட்டுகள், ஆய்வக அறிக்கைகள், டிஸ்சார்ஜ் சுருக்கங்கள் — JPG, PNG, அல்லது PDF, ஒவ்வொன்றும் 15MB வரை",
    skipStep: "இந்த படியைத் தவிர்",
    continueSummary: "சுருக்கத்திற்குச் செல்",
    buildingSummary: "உங்கள் வரலாற்று சுருக்கம் உருவாக்கப்படுகிறது…",
    buildingSummarySub: "MediKiosk உங்கள் பதில்களையும் ஆவணங்களையும் ஒரு மருத்துவ சுருக்கமாக இணைக்கிறது.",
    summaryReady: "உங்கள் வரலாறு தயார்",
    summaryReadyBody: "தயவுசெய்து கேட்டு உறுதிப்படுத்தவும் — உங்கள் மருத்துவர் ஆலோசனையின்போது இதை மதிப்பாய்வு செய்வார்.",
    confirmSend: "உறுதிப்படுத்தி மருத்துவருக்கு அனுப்பு",
    sentTitle: "உங்கள் மருத்துவருக்கு அனுப்பப்பட்டது",
    sentBody: "உங்கள் வரலாறு உங்கள் ABHA பதிவுடன் இணைக்கப்பட்டு மருத்துவமனை அமைப்பிற்கு அனுப்பப்பட்டுள்ளது. தயவுசெய்து அமரவும் — விரைவில் உங்கள் டோக்கன் எண் அழைக்கப்படும்.",
    seePhysician: "மருத்துவர் என்ன பார்க்கிறார் என்பதைப் பார் →",
  },
  bn: {
    consentTitle: "আপনার পরিচয় ও সম্মতি নিশ্চিত করুন",
    consentSub: "আয়ুষ্মান ভারত ডিজিটাল মিশনের অধীনে আপনার ইতিহাস আপনার ABHA স্বাস্থ্য অ্যাকাউন্টের সাথে যুক্ত।",
    abhaLabel: "ABHA আইডি বা আধার-সংযুক্ত নম্বর",
    newPatient: "নতুন রোগী — ABHA ছাড়া নিবন্ধন করুন →",
    consentStore: "আমি সম্মতি দিচ্ছি যে আমার বলা ইতিহাস এবং স্ক্যান করা নথি আমার মেডিকেল রেকর্ড তৈরি করতে ব্যবহৃত হবে।",
    consentShare: "আমি সম্মতি দিচ্ছি যে এই রেকর্ড আমার চিকিৎসকের সাথে শেয়ার করা হবে এবং আমার ABHA অ্যাকাউন্টের সাথে যুক্ত করা হবে।",
    consentAudio: "এগিয়ে যাওয়ার আগে এই সম্মতিটি আমার ভাষায় পড়ে শোনান।",
    agreeBtn: "সম্মত এবং ইতিহাস শুরু করুন",
    questionsAnswered: (n) => `এখন পর্যন্ত ${n}টি প্রশ্নের উত্তর দেওয়া হয়েছে`,
    priorityTitle: "অগ্রাধিকার সতর্কতা জারি করা হয়েছে।",
    priorityBody: "ট্রায়াজ কর্মীদের জানানো হয়েছে — এই রোগীকে সিরিয়াল ছাড়াই দেখা হবে।",
    micListening: "শুনছে…",
    micIdle: "অথবা আপনার উত্তর টাইপ করুন / বলুন",
    nextBtn: "পরবর্তী",
    micUnsupported: "এই ব্রাউজারে ভয়েস ইনপুট সমর্থিত নয়। অনুগ্রহ করে টাইপ করুন, অথবা Chrome ব্যবহার করুন।",
    micDenied: "মাইক্রোফোন অ্যাক্সেস ব্লক করা আছে। এই সাইটের জন্য মাইক্রোফোন অনুমতি দিন এবং আবার চেষ্টা করুন।",
    micNoSpeech: "স্পষ্ট শোনা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন বা টাইপ করুন।",
    micGenericError: "ভয়েস ইনপুটে সমস্যা হয়েছে। অনুগ্রহ করে টাইপ করুন।",
    scanTitle: "আপনার পূর্ববর্তী মেডিকেল নথি স্ক্যান করুন",
    scanSub: "আপনার কাছে প্রেসক্রিপশন, ল্যাব রিপোর্ট বা ডিসচার্জ সামারি থাকলে তার ছবি বা PDF আপলোড করুন।",
    uploadPrompt: "আপলোড করতে ট্যাপ করুন, বা ফাইল এখানে টেনে আনুন",
    uploadHint: "প্রেসক্রিপশন, ল্যাব রিপোর্ট, ডিসচার্জ সামারি — JPG, PNG, বা PDF, প্রতিটি 15MB পর্যন্ত",
    skipStep: "এই ধাপ এড়িয়ে যান",
    continueSummary: "সারাংশে এগিয়ে যান",
    buildingSummary: "আপনার ইতিহাসের সারাংশ তৈরি হচ্ছে…",
    buildingSummarySub: "MediKiosk আপনার উত্তর ও নথিগুলিকে একটি ক্লিনিক্যাল সারাংশে একত্র করছে।",
    summaryReady: "আপনার ইতিহাস প্রস্তুত",
    summaryReadyBody: "অনুগ্রহ করে শুনুন এবং নিশ্চিত করুন — আপনার চিকিৎসক পরামর্শের সময় এটি পর্যালোচনা করবেন।",
    confirmSend: "নিশ্চিত করুন এবং চিকিৎসকের কাছে পাঠান",
    sentTitle: "আপনার ডাক্তারের কাছে পাঠানো হয়েছে",
    sentBody: "আপনার ইতিহাস আপনার ABHA রেকর্ডের সাথে যুক্ত করে হাসপাতাল সিস্টেমে পাঠানো হয়েছে। অনুগ্রহ করে বসুন — শীঘ্রই আপনার টোকেন নম্বর ডাকা হবে।",
    seePhysician: "চিকিৎসক কী দেখেন তা দেখুন →",
  },
};
