const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
const http = require("http");
const WebSocket = require("ws");
const { GoogleGenAI } = require("@google/genai");

dotenv.config();

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY
});
const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

// ====================
// BASIC HEALTH CHECK
// ====================
app.get("/api/health", (req, res) => {
  res.json({
    success: true,
    message: "MediKiosk backend is running!"
  });
});

// ====================
// DEMO AUTH ROUTES
// ====================

// Google login
app.post("/api/auth/google", (req, res) => {
  res.json({
    success: true,
    token: "demo-google-token",
    user: {
      id: "patient-demo",
      name: "Demo Patient",
      role: "patient"
    }
  });
});

// Patient session
app.post("/api/auth/patient-session", (req, res) => {
  res.json({
    success: true,
    token: "demo-patient-token",
    user: {
      id: "patient-demo",
      name: "Demo Patient",
      role: "patient"
    }
  });
});

// Staff signup
app.post("/api/auth/staff/signup", (req, res) => {
  res.json({
    success: true,
    message: "Staff account created successfully",
    token: "demo-staff-token"
  });
});

// Staff login
app.post("/api/auth/staff/login", (req, res) => {
  res.json({
    success: true,
    token: "demo-staff-token",
    user: {
      id: "doctor-demo",
      name: "Demo Doctor",
      role: "staff"
    }
  });
});

// ====================
// AI ROUTES - DEMO
// ====================

app.post("/api/claude/summary", (req, res) => {
  res.json({
    success: true,
    summary:
      "This is a demo clinical summary generated by the MediKiosk backend."
  });
});

app.post("/api/claude/chat", async (req, res) => {
  try {
    const { message, messages } = req.body;

    const userMessage =
      message ||
      messages?.[messages.length - 1]?.content ||
      "";

    if (!userMessage.trim()) {
      return res.status(400).json({
        success: false,
        message: "Message is required"
      });
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `
You are MediKiosk AI Assistant, a healthcare information assistant
inside a hospital patient kiosk.

Your job is to:
- Understand the patient's message.
- Ask simple follow-up questions when useful.
- Give clear, easy-to-understand health information.
- Help the patient decide what type of healthcare service may be appropriate.
- Encourage appropriate professional medical care when necessary.
- If the patient describes potentially serious or emergency symptoms,
  clearly recommend seeking immediate emergency medical help.

Important:
- Do not claim to diagnose the patient.
- Do not prescribe medicines or give medication dosages.
- Do not pretend to be a doctor.
- Keep responses concise and patient-friendly.
- Never ask for passwords, API keys, payment information, or other secrets.

Patient message:
${userMessage}
              `
            }
          ]
        }
      ]
    });

    const reply = response.text || "I'm sorry, I couldn't generate a response.";

    res.json({
      success: true,
      reply
    });

  } catch (error) {
    console.error("Gemini API error:", error);

    res.status(500).json({
      success: false,
      message: "AI assistant is temporarily unavailable."
    });
  }
});

// ====================
// MEDICATION ROUTES
// ====================

let medicationLogs = {};

app.post("/api/medication/log", (req, res) => {
  const { date, taken } = req.body;

  if (!date) {
    return res.status(400).json({
      success: false,
      message: "Date is required"
    });
  }

  medicationLogs[date] = Boolean(taken);

  res.json({
    success: true,
    date,
    taken: Boolean(taken)
  });
});

app.get("/api/medication/log", (req, res) => {
  res.json({
    success: true,
    logs: medicationLogs
  });
});
// ====================
// PHARMACY / MEDICINE ROUTES
// ====================

// Demo medicine inventory
let medicines = [
  {
    id: "MED001",
    name: "Paracetamol",
    category: "Pain Relief",
    price: 20,
    stock: 50,
    requiresPrescription: false
  },
  {
    id: "MED002",
    name: "Cetirizine",
    category: "Allergy",
    price: 30,
    stock: 40,
    requiresPrescription: false
  },
  {
    id: "MED003",
    name: "Cough Syrup",
    category: "Cough & Cold",
    price: 80,
    stock: 25,
    requiresPrescription: false
  },
  {
    id: "MED004",
    name: "Vitamin Tablets",
    category: "Vitamins",
    price: 120,
    stock: 30,
    requiresPrescription: false
  }
];

// Demo orders
let pharmacyOrders = [];

// --------------------
// GET MEDICINES
// --------------------
app.get("/api/pharmacy/medicines", (req, res) => {
  res.json({
    success: true,
    medicines
  });
});

// --------------------
// ADD MEDICINE
// --------------------
app.post("/api/pharmacy/medicines", (req, res) => {
  const {
    name,
    category,
    price,
    stock,
    requiresPrescription
  } = req.body;

  if (!name || price == null || stock == null) {
    return res.status(400).json({
      success: false,
      message: "Name, price and stock are required"
    });
  }

  const medicine = {
    id: `MED${String(medicines.length + 1).padStart(3, "0")}`,
    name: String(name).trim(),
    category: category || "General",
    price: Number(price),
    stock: Number(stock),
    requiresPrescription: Boolean(requiresPrescription)
  };

  medicines.push(medicine);

  res.status(201).json({
    success: true,
    medicine
  });
});

// --------------------
// CREATE PHARMACY ORDER
// --------------------
app.post("/api/pharmacy/orders", (req, res) => {
  const {
    patientName,
    phone,
    address,
    paymentMethod,
    items
  } = req.body;

  if (!patientName || !phone || !address) {
    return res.status(400).json({
      success: false,
      message: "Patient name, phone and address are required"
    });
  }

  if (!Array.isArray(items) || items.length === 0) {
    return res.status(400).json({
      success: false,
      message: "At least one medicine is required"
    });
  }

  // Validate medicines and calculate total
  let total = 0;

  for (const item of items) {
    const medicine = medicines.find(
      m => m.id === item.id
    );

    if (!medicine) {
      return res.status(400).json({
        success: false,
        message: `Medicine ${item.id} not found`
      });
    }

    const quantity = Number(item.quantity);

    if (!Number.isInteger(quantity) || quantity < 1) {
      return res.status(400).json({
        success: false,
        message: "Invalid medicine quantity"
      });
    }

    if (medicine.stock < quantity) {
      return res.status(400).json({
        success: false,
        message: `${medicine.name} is out of stock`
      });
    }

    total += medicine.price * quantity;
  }

  // Reduce stock
  for (const item of items) {
    const medicine = medicines.find(
      m => m.id === item.id
    );

    medicine.stock -= Number(item.quantity);
  }

  const order = {
    id: `ORD-${Date.now()}`,
    patientName: String(patientName).trim(),
    phone: String(phone).trim(),
    address: String(address).trim(),
    paymentMethod: paymentMethod || "Cash",
    items,
    total,
    status: "pending",
    createdAt: new Date().toISOString()
  };

  pharmacyOrders.push(order);

  res.status(201).json({
    success: true,
    message: "Pharmacy order created successfully",
    order
  });
});

// --------------------
// GET ALL PHARMACY ORDERS
// --------------------
app.get("/api/pharmacy/orders", (req, res) => {
  res.json({
    success: true,
    orders: pharmacyOrders
  });
});

// --------------------
// GET SINGLE ORDER
// --------------------
app.get("/api/pharmacy/orders/:id", (req, res) => {
  const order = pharmacyOrders.find(
    o => o.id === req.params.id
  );

  if (!order) {
    return res.status(404).json({
      success: false,
      message: "Order not found"
    });
  }

  res.json({
    success: true,
    order
  });
});

// --------------------
// UPDATE ORDER STATUS
// --------------------
app.patch("/api/pharmacy/orders/:id/status", (req, res) => {
  const { status } = req.body;

  const allowedStatuses = [
    "pending",
    "confirmed",
    "ready",
    "completed",
    "cancelled"
  ];

  if (!allowedStatuses.includes(status)) {
    return res.status(400).json({
      success: false,
      message: "Invalid order status"
    });
  }

  const order = pharmacyOrders.find(
    o => o.id === req.params.id
  );

  if (!order) {
    return res.status(404).json({
      success: false,
      message: "Order not found"
    });
  }

  order.status = status;
  order.updatedAt = new Date().toISOString();

  res.json({
    success: true,
    message: "Order status updated",
    order
  });
});

// ====================
// HTTP SERVER
// ====================

const server = http.createServer(app);

// ====================
// WEBSOCKET SERVER
// ====================

const wss = new WebSocket.Server({
  server,
  path: "/ws/messaging"
});

const clients = new Map();

wss.on("connection", (ws) => {
  console.log("WebSocket client connected");

  let clientId = null;

  ws.on("message", (message) => {
    try {
      const data = JSON.parse(message.toString());

      // Register encryption key
      if (data.type === "register_key") {
        clientId = data.userId || `client-${Date.now()}`;

        clients.set(clientId, {
          ws,
          publicKeyJwk: data.publicKeyJwk
        });

        ws.send(
          JSON.stringify({
            type: "registered",
            userId: clientId
          })
        );

        console.log("Client registered:", clientId);
      }

      // Request doctor list
      else if (data.type === "request_doctor_list") {
        const doctors = [];

        for (const [id, client] of clients.entries()) {
          if (id.startsWith("doctor")) {
            doctors.push({
              id,
              name: "Demo Doctor",
              available: true,
              publicKeyJwk: client.publicKeyJwk
            });
          }
        }

        ws.send(
          JSON.stringify({
            type: "doctor_list",
            doctors
          })
        );
      }

      // Send encrypted message
      else if (data.type === "send_message") {
        const recipient = clients.get(data.to);

        if (!recipient) {
          ws.send(
            JSON.stringify({
              type: "error",
              error: "Doctor is not currently connected."
            })
          );
          return;
        }

        recipient.ws.send(
          JSON.stringify({
            type: "message",
            from: clientId,
            senderPublicKeyJwk:
              clients.get(clientId)?.publicKeyJwk,
            ciphertext: data.ciphertext,
            iv: data.iv,
            senderName: "MediKiosk User"
          })
        );
      }

      // Doctor availability
      else if (data.type === "set_availability") {
        console.log(
          `Client ${clientId} availability:`,
          data.available
        );
      }
    } catch (error) {
      console.error("WebSocket message error:", error);

      ws.send(
        JSON.stringify({
          type: "error",
          error: "Invalid WebSocket message."
        })
      );
    }
  });

  ws.on("close", () => {
    if (clientId) {
      clients.delete(clientId);
      console.log("Client disconnected:", clientId);
    }
  });
});

// ====================
// START SERVER
// ====================

server.listen(PORT, () => {
  console.log(
    `MediKiosk backend running at http://localhost:${PORT}`
  );
  console.log(
    `WebSocket messaging running at ws://localhost:${PORT}/ws/messaging`
  );
});
